run:
  timeout: 5m
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences